//let elso = document.getElementById("elso");
//let masodik = document.getElementById("masodik");
//elso.addEventListener("click", () =>{
//    let tarto = document.getElementById("tarto");
//    let masiktarto=document.createElement("div");
//    masiktarto.setAttribute("id", "tarto");
//    masiktarto.innerHTML = "<h1>Ez egy másik fejléc</h1>";
//    masiktarto.innerHTML = "<button id='masodik'>masodik gomb</button>";
//    document.body.replaceChild(masiktarto, tarto);
//});



let eGomb = document.getElementById('e');
eGomb.addEventListener("click", () => {
    let content = document.getElementById("content");

    let masikContent = document.createElement("div");
    masikContent.setAttribute("id", "content");
    masikContent.innerHTML = "<h2>E Csoport</h2>";
    masikContent.innerHTML += "<div class='csapatok'><h3>Atlético Madrid</h3> <p>Az Atlético de Madrid, teljes nevén Club Atlético de Madrid S.A.D. spanyol, madridi székhelyű futballklub, otthona sokáig a Manzanares folyó melletti Vicente Calderón stadion volt, de 2017-ben átadták új stadionját, a Wanda Metropolitano Stadiont. Az Atlético 11-szer nyerte meg a spanyol bajnokságot, és ugyanennyiszer a spanyol kupát is. 1962-ben a csapat elhódította Kupagyőztesek Európa-kupáját és 1974-ben megnyerte az Interkontinentális kupát. 2010-ben és 2012-ben is megnyerték az Európa-ligát, majd mindkét évben megnyerték az UEFA-szuperkupát is. Az utóbbi döntőben a kolumbiai Radamel Falcao mesterhármast szerzett. 2013-ban, 17 év után nyerte meg a Spanyol labdarúgókupát. Eddig háromszor jutott be a BEK/BL döntőjébe, ám mindháromszor alulmaradtak, az 1973-74-es szezon végén a FC Bayern München, a 2013-14-es, és a 2015-16-os döntőben pedig a Real Madrid CF ellen.</p> <img class='pic' src='https://cdn.discordapp.com/attachments/1153583327169753139/1173912434612899860/Atletico_Madrid_2017_logo.png?ex=6565ae26&is=65533926&hm=c667508690ba55c8982b758f0d70ede20d184f299bfc5fa4e0aa66ee78146529&' alt='Atlético Madrid'></div>";
    masikContent.innerHTML += "<div class='csapatok'><h3>SS Lazio</h3> <p>Az SS Lazio (teljes nevén Società Sportiva Lazio) egy Olaszországban, Rómában székelő sportegyesület rövidítése. Gyakran egyszerűen Lazio néven emlegetik. Székhelye Róma, Lazio tartományban, innen a neve is. A legnagyobb európai sportegyesületek egyike, 37 sportággal, többek közt krikett, kosárlabda, ejtőernyőzés.[1] A legfontosabb sportága a férfi labdarúgás. Fő riválisa az AS Roma. Jobboldali szellemű csapat, ezért is a kiélezett küzdelem a Romával, mert az inkább „balos”. Sok híres focista fordult itt meg (Nedved, Crespo, Stankovic, Vieri), de őket később gazdagabb klubok elvitték. Két alkalommal, 1974 és 2000 évben volt Serie A bajnok. Hétszer nyert Olasz Kupát. 1937-ben legendás meccset játszott az FTC-vel, ahol 4:2 arányban vereséget szenvedett. Hírhedt szurkoló tábora van, amelyik Irriducibili névre hallgatott. Jelenlegi kapitányuk Ciro Immobile. Legendás csapatkapitánya di Canio volt.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/S.S._Lazio_logo.svg/1665px-S.S._Lazio_logo.svg.png' alt='SS Lazio'></div>";
    masikContent.innerHTML += "<div class='csapatok'><h3>Feyenoord</h3> <p>A klub játékosai szinte minden egyes évben harcba szállnak és harcban állnak a holland bajnoki címért folytatott küzdelemben. Ennek következtében napjainkig tizenöt alkalommal végeztek a képzeletbeli bajnoki dobogó legtetején, számtalanszor hódították el a holland kupát. Ugyanakkor nemzetközi szinten is szép sikereket könyvelhet el a klub, legutóbbi kimagasló eredményüket a 2002-es UEFA kupáért folytatott küzdelemben mutatták fel, ekkor megnyerték a sorozatot. A csapat a 2021-2022-es szezonban bejutott az UEFA Európa Konferencia Liga döntőjébe, ahol az olasz AS Roma együttesétől 1-0 arányban vereséget szenvedtek.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Feyenoord_logo.svg/640px-Feyenoord_logo.svg.png' alt='Feyenoord'></div>";
    masikContent.innerHTML += "<div class='csapatok'><h3>Celtic FC</h3> <p>A Celtic Football Club , közismert nevén Celtic (/ˈs ɛ t ɪ k / SEL - tik ) , egy glasgow - i székhelyű skót profi futballklub , amely a skót élvonalban játszik . A klubot 1887-ben alapították [nb 1] azzal a céllal, hogy enyhítse a bevándorló ír lakosság szegénységét Glasgow East End -ében . Első meccsüket 1888 májusában játszották, a Rangers elleni barátságos mérkőzésen , amelyet a Celtic 5–2-re megnyert. A Celtic meghonosodott a skót futballban, és a 20. század első évtizedében egymás után hat bajnoki címet nyert. A klub legnagyobb sikereit az 1960-as és 70-es években érte el Jock Stein vezetésével, amikor egymás után kilenc bajnoki címet és 1967-es Európa Kupát nyertek . A Celtic történelme során zöld-fehérben játszott, 1903-ban átvette az azóta is használt karikákat.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Celtic_FC.svg/1200px-Celtic_FC.svg.png' alt='Celtic FC'></div>";
    masikContent.innerHTML += "<div class='table'><table><thead><tr><td>Állás</td><td>Lejátszott</td><td>Nyert</td><td>Döntetlen</td><td>vesztett</td><td>pontok</td></tr><thead><tbody><tr><th>1. Atlético Mardid</th><td>4</td><td>2</td><td>2</td><td>0</td><td>8</td></tr><tr><th>2. SS Lazio</th><td>4</td><td>2</td><td>1</td><td>1</td><td>7</td></tr><tr><th>3. Feyenoord</th><td>4</td><td>2</td><td>0</td><td>2</td><td>6</td></tr><tr><th>4. Celtic FC</th><td>4</td><td>0</td><td>1</td><td>3</td><td>1</td></tr></tbody></table></div>";
    document.body.replaceChild(masikContent, content);
});


let fGomb = document.getElementById('f');
fGomb.addEventListener("click", () => {
    let content = document.getElementById("content");

    let masikContent2 = document.createElement("div");
    masikContent2.setAttribute("id", "content");
    masikContent2.innerHTML = "<h2>F Csoport</h2>";
    masikContent2.innerHTML += "<div class='csapatok'><h3>Borussia Durtmund</h3> <p>A Borussia Dortmund (rövidítéseiben: BVB vagy BVB 09) német sportegyesület, székhelye Dortmund. A BVB Németország egyik legsikeresebb klubja, egyben az első német csapat, amely nemzetközi trófeát nyert (1966, KEK). Sikereinek csúcsát 1997-ben Ottmar Hitzfeld irányítása alatt érte el, többek között az UEFA Bajnokok Ligáját, majd ezt követően az interkontinentális kupát is elhódította. A Borussia Dortmund jelenleg is a Bundesligában játszik, és a harmadik helyen áll a német örökranglistán. Legutóbbi bajnoki címét a 2011-12-es szezonban, Jürgen Klopp vezetőedző irányításával érte el. A dortmundi futballcsapatot nemcsak a múltja, hanem egyedülálló szurkolótábora miatt is Európa legnagyobb klubjai közé sorolják. A 81 264 néző befogadására alkalmas Signal Iduna Park minden mérkőzésen megtelik, a dortmundi átlagnézőszám egyedülálló Európában. Habár a Borussia Dortmundot eredetileg labdarúgó szakosztályként alapították, van egy kézilabda és asztalitenisz szakosztálya is. A tagok száma az egyesületben kb. 35 000 fő.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/800px-Borussia_Dortmund_logo.svg.png' alt='Borussia Durtmund'></div>";
    masikContent2.innerHTML += "<div class='csapatok'><h3>Paris Saint-Germain</h3> <p>A Paris Saint-Germain Football Club (rövidítve: Paris SG vagy PSG) francia labdarúgócsapatot 1970-ben alapítottak a francia fővárosban, Párizsban. A PSG nemcsak Párizs, de Franciaország egyik legmeghatározóbb, legismertebb focicsapata is. A klub stadionja a Parc des Princes, amely 46 480 néző befogadására alkalmas. 1974-es feljutása óta folyamatosan a francia első osztály (Ligue 1) tagja. Alapító tagja volt a G-14 nevű konglomerátumnak, melyet az Európai Klubszövetség váltott fel.777777</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/1200px-Paris_Saint-Germain_F.C..svg.png' alt='PSG'></div>";
    masikContent2.innerHTML += "<div class='csapatok'><h3>AC Milan</h3> <p>Az Associazione Calcio Milan (rövidítve AC Milan vagy egyszerűen Milan) egy olasz labdarúgócsapat Milánóban, Lombardiában. 1899-ben alapították és fennállása óta szinte minden idényét az olasz futball élvonalában, a Serie A-ban töltötte. A világ egyik legjelentősebb labdarúgó klubja. Eddig összesen 47 trófeát nyert a csapat, közte 19 bajnoki címet és 7 Bajnokok Ligáját. A klub eddig, minden más csapatnál több, 5 alkalommal nyert Európai szuperkupát, és 4 alkalommal pedig interkontinentális kupát. A címek között szerepel még 2 KEK, valamint 5 olasz kupa és 7 olasz szuperkupa. Világrekordnak számító 18 nemzetközi trófeájával a világ legeredményesebb klubja.</p> <img class='pic' src='https://www.acmilan.com/images/social/acmilan.png' alt='Milan'></div>";
    masikContent2.innerHTML += "<div class='csapatok'><h3>Newcastle United</h3> <p>A Newcastle United Football Club egy professzionális futballklub , amelynek székhelye az angliai Newcastle upon Tyne , Tyne and Wear. A csapat a 2023–2024-es szezontól a Premier League- ben, az angol labdarúgó-bajnokság első szintjén versenyez . A klub 1892-es megalakulása óta, amikor a Newcastle East End felvette a Newcastle West End vagyonát , és Newcastle Uniteddé vált, a klub hazai mérkőzéseit a St James' Parkban játszotta . Newcastle központjában található, jelenleg 52 305 férőhelyes.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/300px-Newcastle_United_Logo.svg.png' alt='Newcastle'></div>";
    masikContent2.innerHTML += "<div class='table'><table><thead><tr><td>Állás</td><td>Lejátszott</td><td>Nyert</td><td>Döntetlen</td><td>vesztett</td><td>pontok</td></tr><thead><tbody><tr><th>1. Dortmund</th><td>4</td><td>2</td><td>1</td><td>1</td><td>7</td></tr><tr><th>2. Paris Saint-Germain</th><td>4</td><td>2</td><td>0</td><td>2</td><td>6</td></tr><tr><th>3. AC Milan</th><td>4</td><td>1</td><td>2</td><td>1</td><td>5</td></tr><tr><th>4. Newcastle United</th><td>4</td><td>1</td><td>1</td><td>2</td><td>4</td></tr></tbody></table></div>";
    document.body.replaceChild(masikContent2, content);
});


let gGomb = document.getElementById('g');
gGomb.addEventListener("click", () => {
    let content = document.getElementById("content");

    let masikContent3 = document.createElement("div");
    masikContent3.setAttribute("id", "content");
    masikContent3.innerHTML = "<h2>G Csoport</h2>";
    masikContent3.innerHTML += "<div class='csapatok'><h3>Manchester City</h3> <p>A Manchester City Football Club az angol legfelső osztályban (Premier League) játszó manchesteri labdarúgóklub. 1880-ban alapították West Gorton (St. Marks) néven, a klub neve 1887-ben Ardwick AFC lett, mai nevét 1894-ben kapta. Kilencszer nyerte meg az angol bajnokságot. Hétszer lett angol kupagyőztes, nyolcszor ligakupa-győztes, valamint hatszor szuperkupa-győztes. Nemzetközi porondon pedig egyszer-egyszer sikerült a csúcsra érni az UEFA-bajnokok ligájában, valamint a Kupagyőztesek Európa-kupájában, csakúgy egyszer az UEFA-szuperkupában is.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/800px-Manchester_City_FC_badge.svg.png' alt='Mancity'></div>";
    masikContent3.innerHTML += "<div class='csapatok'><h3>Leipzig</h3> <p>Rasen Ballsport Leipzig német futballcsapat, székhelye Lipcse.[2] Az energiaital gyártó cég – a Red Bull − 2009-ben felvásárolta a SSV Markranstädt együttesét azzal a céllal, hogy 10 éven belül a Bundesligában szerepeljen az együttes. A 2009-10-es szezonban az ötödosztályból a negyedik vonalba jutottak fel. Két évvel később feljutottak a 3. Ligába. Rögtön első évükben gólkülönbségben lettek másodikak az 1. FC Heidenheim mögött, de így is feljutottak a Bundesliga 2-be. Az első osztályba két év után jutottak fel.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/hu/thumb/f/fd/RB_Leipzig.png/150px-RB_Leipzig.png' alt='Leipzig'></div>";
    masikContent3.innerHTML += "<div class='csapatok'><h3>Crvena zvezda</h3> <p>A Crvena zvezda (szerbül Фудбалски клуб Црвена звезда, latin betűkkel Fudbalski klub Crvena zvezda, magyarul Vörös csillag labdarúgóklub, a külföldi sajtóban gyakran az angol vagy a különböző más nyelvre lefordított verzióban szerepel) szerb labdarúgócsapat, amelynek székhelye a szerb fővárosban, Belgrádban van. A Crvena zvezda a legsikeresebb csapat Szerbiában, a szerb, valamint korábban a jugoszláv bajnokságot huszonötször, a kupát huszonháromszor sikerült megnyernie. A jugoszláv bajnokság örökranglistáján az első helyen zárt. Az egyetlen exjugoszláv csapat, amelyik BEK-et nyert (1991), valamint az egyetlen balkáni, aki elhódította az interkontinentális kupát. Ezen kívül is, a térségben nem túl megszokott módon, számos kisebb-nagyobb nemzetközi sikert tudhat még magáénak, ilyen az UEFA-kupa-döntő 1979-ből, valamint a számos BEK és KEK elődöntő, illetve negyeddöntő.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Grb-fk-crvena-zvezda.svg/150px-Grb-fk-crvena-zvezda.svg.png' alt='Crvezna'></div>";
    masikContent3.innerHTML += "<div class='csapatok'><h3>Young Boys</h3> <p>A BSC Young Boys a svájci főváros, Bern egyik labdarúgócsapata. Az FC Young Boys-t 1898. március 14-én alapították, neve egy létező klub, az Old Boys Basel ellentéte. Első meccsüket az FC Viktoria ellen játszották 1898. június 17-én. 1925-ben a klub átköltözött az újonnan épült Wankdorf Stadionba és az FC előtagot BSC-re változtatták (Berner Sport Club – Berni Sport Klub) elfogadva azt a tényt, hogy a klub nemcsak labdarúgócsapat volt, hanem bocsa-, kézilabda- és gyeplabdacsapat is.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/BSC_Young_Boys.svg/150px-BSC_Young_Boys.svg.png' alt='Young Boys'></div>";
    masikContent3.innerHTML += "<div class='table'><table><thead><tr><td>Állás</td><td>Lejátszott</td><td>Nyert</td><td>Döntetlen</td><td>vesztett</td><td>pontok</td></tr><thead><tbody><tr><th>1. Manchester City</th><td>4</td><td>4</td><td>0</td><td>0</td><td>12</td></tr><tr><th>2. RB Leipzig</th><td>4</td><td>3</td><td>0</td><td>1</td><td>9</td></tr><tr><th>3. Crvena Zvezda</th><td>4</td><td>0</td><td>1</td><td>3</td><td>1</td></tr><tr><th>4. Young Boys</th><td>4</td><td>0</td><td>1</td><td>3</td><td>1</td></tr></tbody></table></div>";
    document.body.replaceChild(masikContent3, content);
});


let hGomb = document.getElementById('h');
hGomb.addEventListener("click", () => {
    let content = document.getElementById("content");

    let masikContent4 = document.createElement("div");
    masikContent4.setAttribute("id", "content");
    masikContent4.innerHTML = "<h2>H Csoport</h2>";
    masikContent4.innerHTML += "<div class='csapatok'><h3>Barcelona</h3> <p>Az FC Barcelona Spanyolország Katalónia tartományának labdarúgócsapata. A klub a spanyol labdarúgó-bajnokság kezdetétől megszakítás nélkül részt vesz az első osztály bajnoki küzdelmeiben. Az egyesületet 1899. november 29-én alapította a svájci Hans Gamper. Az FC Barcelona előbb a katalán regionális bajnokságban és a spanyol labdarúgókupában, később pedig az 1928-ban megalakított egységes spanyol labdarúgó-bajnokságban és a nemzetközi kupákban vált a spanyol, valamint a nemzetközi labdarúgás egyik legmeghatározóbb egyesületévé.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/FC_Barcelona_crest.svg/150px-FC_Barcelona_crest.svg.png' alt='FC Barcelona'></div>";
    masikContent4.innerHTML += "<div class='csapatok'><h3>Porto</h3> <p>A Futebol Clube do Porto (röviden FC Porto) Portugália egyik legismertebb és legsikeresebb labdarúgócsapata. A 2003–04-es szezonban megnyerte a Bajnokok Ligája sorozatot, legutóbb pedig a bajnokság mellett a 2010–11-es Európa-ligát.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/FC_Porto.svg/255px-FC_Porto.svg.png' alt='FC Porto'></div>";
    masikContent4.innerHTML += "<div class='csapatok'><h3>Shakhtar</h3> <p>A Sahtar Doneck (ukrán betűkkel Футбольний клуб Шахтар Донецьк, magyar átírásban Futbolnij klub Sahtar Doneck, a nemzetközi sajtóban FC Shakhtar Donetsk) ukrán labdarúgócsapat Doneckben, Ukrajnában. A kelet-ukrajnai háború miatt a csapat központja Kijevbe költözött, ahol edzéseiket is tartják. A hazai mérkőzéseket 2014–2016 között a Lviv Arénában játszották, 2017-től pedig a harkivi Metaliszt stadionban játsszák.</p> <img class='pic' src='https://logowik.com/content/uploads/images/fc-shakhtar-donetsk3810.jpg' alt='Shaktar Donetsk'></div>";
    masikContent4.innerHTML += "<div class='csapatok'><h3>Antwerp</h3> <p>A Royal Antwerp Football Club, gyakran egyszerűen csak Antwerp, egy belga labdarúgócsapat Antwerpenben. Az Antwerp tekinthető a legidősebb belga labdarúgóklubnak, nagyjából 1880-ban alapították Antwerpenben tanuló angol diákok Antwerp Athletic Club néven, 15 évvel a Belga labdarúgó-szövetség megalapítása előtt. A kezdetekben még nem volt szervezett labdarúgás a klubon belül, csak 1887-ben alapították meg az Antwerp Football Club nevű önálló részleget. Ez a legidősebb csapat, amelyik a szövetség 1895-ös megalakulása óta folyamatosan profi szinten játszik, az 1-es regisztrációs számmal (matricule) rendelkezik, ezeket a rendszámokat 1926-tól osztják ki.</p> <img class='pic' src='https://upload.wikimedia.org/wikipedia/en/thumb/0/0b/Royal_Antwerp_Football_Club_logo.svg/800px-Royal_Antwerp_Football_Club_logo.svg.png' alt='Fc Antwerp'></div>";
    masikContent4.innerHTML += "<div class='table'><table><thead><tr><td>Állás</td><td>Lejátszott</td><td>Nyert</td><td>Döntetlen</td><td>vesztett</td><td>pontok</td></tr><thead><tbody><tr><th>1. Barcelona</th><td>4</td><td>3</td><td>0</td><td>1</td><td>9</td></tr><tr><th>2. Fc Porto</th><td>4</td><td>3</td><td>0</td><td>1</td><td>9</td></tr><tr><th>3. Shakhtar Donetsk</th><td>4</td><td>2</td><td>0</td><td>2</td><td>6</td></tr><tr><th>4. Antwerp</th><td>4</td><td>0</td><td>0</td><td>4</td><td>0</td></tr></tbody></table></div>";
    document.body.replaceChild(masikContent4, content);
});